export const CLUBS = [
  {
    id: 'club-robotics',
    name: 'FPT Robotics Club',
    category: 'Technology',
    members: 148,
    status: 'Recruiting',
    color: '#16685D',
    bg: '#E8F5F0',
    icon: '🤖',
    description: 'Building the future through robotics and automation engineering.',
  },
  {
    id: 'club-creative-media',
    name: 'Creative Media Studio',
    category: 'Arts & Design',
    members: 97,
    status: 'Active',
    color: '#3B82F6',
    bg: '#EFF6FF',
    icon: '🎨',
    description: 'Visual storytelling, photography, video production and digital design.',
  },
  {
    id: 'club-entrehub',
    name: 'EntreHub – Startup Lab',
    category: 'Business',
    members: 212,
    status: 'Recruiting',
    color: '#D97706',
    bg: '#FFFBEB',
    icon: '🚀',
    description: 'Connecting student entrepreneurs with mentors, funding and resources.',
  },
  {
    id: 'club-greenfpt',
    name: 'GreenFPT Environment',
    category: 'Community',
    members: 83,
    status: 'Active',
    color: '#16A34A',
    bg: '#F0FDF4',
    icon: '🌿',
    description: 'Campus sustainability initiatives and environmental awareness campaigns.',
  },
  {
    id: 'club-code-warriors',
    name: 'Code Warriors',
    category: 'Technology',
    members: 176,
    status: 'Recruiting',
    color: '#2563EB',
    bg: '#EFF6FF',
    icon: '💻',
    description: 'Competitive programming, hackathons and open-source contribution.',
  },
  {
    id: 'club-dance',
    name: 'FPT Dance Academy',
    category: 'Performing Arts',
    members: 134,
    status: 'Active',
    color: '#7C3AED',
    bg: '#F5F3FF',
    icon: '💃',
    description: 'Hip-hop, contemporary and traditional Vietnamese dance performances.',
  },
];

export const CATEGORIES = [
  'All',
  'Technology',
  'Arts & Design',
  'Business',
  'Community',
  'Performing Arts',
];